behaviors:
  RobotArticulationMulti:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 512
      learning_rate: 0.0005
      beta: 0.001
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.95
    keep_checkpoints: 10
    checkpoint_interval: 10000
    max_steps: 250000
    time_horizon: 512
    summary_freq: 1000
    framework: tensorflow