behaviors:
  RobotArticulation:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.001
      beta: 0.001
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.98
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 100000
    time_horizon: 128
    summary_freq: 1000
    framework: tensorflow